### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vladbrox** [adithyasource/clear#4]
How do you launch games from Steam in the format steam://rungameid/105600 I searched but didn’t really understand how it was implemented

**Comment by adithyasource** [comment]
Hey there! It's basically this command in windows
```
cmd /C start steam://rungameid/105600
```

It's executed in rust using this function

```
#[tauri::command]
fn open_location(location: &str) {
    let _ = Command::new("cmd")
        .args(&["/C", "start", "", location])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .creation_flags(0x08000000)
        .spawn();
}
```
It'll work even if you provide it a website link, the location of an exe, or in this case, a steam uri
